---
# Exercise 2: Run a playbook that prints “Hello World” on a remote Linux host.

- hosts: linux
  gather_facts: no
  vars:
    ansible_connection: ssh
    ansible_port: 22
    ansible_ssh_private_key_file: MyKeyPair.pem
  tasks:
    - name: Print "Hello World" to stdout
      command: echo "Hello World"